CONFIG = {
    "dataset": "adult",
    "sensitive_name": "sex",
    "binary": True,
    "n_subsample": None,
    "n_batches": None,
    "n_features": None,
    "normalize": True,
    "standardize": False,
    "mpfc": True,
    "msflowfc": True,
    "smpfc": False,
    "miqcp": True,
    "setvars": True,
    "n_clusters": [2, 5, 10, 15],
    "n_seeds": 100,
    "target": "maximum",
    "tolerances": [0.30, 0.10, 0.01],
    "global_time_limit": 3600,
    "plot": False,
}
