CONFIG = {
    "dataset": "census1990",
    "sensitive_name": "iSex",
    "binary": True,
    "n_subsample": None,
    "n_batches": 100,
    "n_features": 25,
    "normalize": True,
    "standardize": False,
    "mpfc": False,
    "msflowfc": True,
    "smpfc": True,
    "miqcp": False,
    "setvars": False,
    "n_clusters": [2, 5, 10, 15],
    "n_seeds": 100,
    "target": "maximum",
    "tolerances": [0.30, 0.10, 0.01],
    "global_time_limit": 3600,
    "plot": False,
}
