CONFIG = {
    "dataset": "synthetic_a",
    "sensitive_name": "X3",
    "binary": False,
    "n_subsample": None,
    "n_batches": None,
    "n_features": None,
    "normalize": True,
    "standardize": False,
    "mpfc": True,
    "msflowfc": True,
    "smpfc": False,
    "miqcp": True,
    "setvars": True,
    "n_clusters": [2, 3, 4, 5],
    "n_seeds": 100,
    "target": "dataset",
    "tolerances": [0.00],
    "global_time_limit": 3600,
    "plot": False,
}
